# Generated by Django 2.0.9 on 2019-01-20 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0010_answer'),
        ('correspondents', '0008_auto_20190117_1515'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='correspondents.Department'),
        ),
        migrations.AddField(
            model_name='user',
            name='surveys',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='surveys.Survey'),
        ),
    ]
