# Generated by Django 2.0.9 on 2019-02-20 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
        ('correspondents', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='correspondents.Department'),
        ),
        migrations.AddField(
            model_name='user',
            name='invitations',
            field=models.ManyToManyField(to='surveys.Invitation'),
        ),
    ]
