# Generated by Django 2.0.9 on 2019-01-20 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0010_answer'),
        ('users', '0002_auto_20190120_2305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='surveys',
        ),
        migrations.AddField(
            model_name='user',
            name='surveys',
            field=models.ManyToManyField(to='surveys.Survey'),
        ),
    ]
