# Generated by Django 2.0.9 on 2019-01-25 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0010_answer'),
        ('users', '0003_auto_20190120_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='invitations',
            field=models.ManyToManyField(to='surveys.Invitation'),
        ),
    ]
