# Generated by Django 2.0.9 on 2019-02-01 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('correspondents', '0008_auto_20190117_1515'),
        ('users', '0005_auto_20190201_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='correspondents.Department'),
        ),
    ]
