# Generated by Django 2.0.9 on 2019-02-20 15:38

from django.db import migrations, models
import django.db.models.deletion
import surveys.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('correspondents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='correspondents.Department')),
            ],
        ),
        migrations.CreateModel(
            name='DisplayLogic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=surveys.models.generate_random_token, max_length=32)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='correspondents.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('text', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DisplayByOptions',
            fields=[
                ('displaylogic_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='surveys.DisplayLogic')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('surveys.displaylogic',),
        ),
        migrations.CreateModel(
            name='DisplayByValue',
            fields=[
                ('displaylogic_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='surveys.DisplayLogic')),
                ('value', models.CharField(max_length=100)),
                ('condition', models.CharField(choices=[('==', '=='), ('>=', '>='), ('<=', '<='), ('contains', 'contains'), ('containsNoCase', 'containsNoCase')], default='==', max_length=20)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('surveys.displaylogic',),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('element_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='surveys.Element')),
                ('code', models.CharField(max_length=40)),
                ('text', models.TextField(blank=True)),
                ('help_text', models.TextField(blank=True)),
                ('qtype', models.CharField(choices=[('SINGLECHOICE', 'Radio'), ('MULTICHOICE', 'Checkboxes'), ('SELECT', 'Select (Dropdown)'), ('TEXT', 'Text'), ('ESSAY', 'Essay'), ('INTEGER', 'Integer'), ('EMAIL', 'Email')], default='SINGLECHOICE', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
            bases=('surveys.element',),
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('element_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='surveys.Element')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.Survey')),
            ],
            options={
                'ordering': ['order'],
            },
            bases=('surveys.element',),
        ),
        migrations.AddField(
            model_name='invitation',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.Survey'),
        ),
        migrations.AddField(
            model_name='element',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_surveys.element_set+', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='displaylogic',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_surveys.displaylogic_set+', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='displaylogic',
            name='shown_element',
            field=models.ForeignKey(null=True, on_delete=surveys.models.NON_POLYMORPHIC_CASCADE, related_name='trigger_questions', to='surveys.Element'),
        ),
        migrations.AddField(
            model_name='answer',
            name='options',
            field=models.ManyToManyField(to='surveys.Option'),
        ),
        migrations.AddField(
            model_name='answer',
            name='value',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='surveys.Value'),
        ),
        migrations.AddField(
            model_name='question',
            name='parent_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.Section'),
        ),
        migrations.AddField(
            model_name='option',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.Question'),
        ),
        migrations.AddField(
            model_name='displaylogic',
            name='trigger_question',
            field=models.ForeignKey(null=True, on_delete=surveys.models.NON_POLYMORPHIC_CASCADE, related_name='shown_element', to='surveys.Question'),
        ),
        migrations.AddField(
            model_name='displaybyoptions',
            name='options',
            field=models.ManyToManyField(to='surveys.Option'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.Question'),
        ),
    ]
