# Generated by Django 2.0.9 on 2019-02-21 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='code',
            field=models.CharField(default='code', max_length=40),
            preserve_default=False,
        ),
    ]
