# Generated by Django 2.0.9 on 2019-01-10 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_auto_20190109_1614'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='option',
            options={'ordering': ['code']},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['code']},
        ),
        migrations.AlterField(
            model_name='question',
            name='code',
            field=models.CharField(max_length=40),
        ),
    ]
