# Generated by Django 2.0.9 on 2019-01-10 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("surveys", "0003_auto_20190110_1231")]

    operations = [
        migrations.AlterModelOptions(name="option", options={"ordering": ["order"]}),
        migrations.AddField(
            model_name="option",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
