# Generated by Django 2.0.9 on 2019-01-10 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("surveys", "0004_auto_20190110_2250")]

    operations = [
        migrations.AlterModelOptions(name="question", options={"ordering": ["order"]}),
        migrations.AddField(
            model_name="question",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
