# Generated by Django 2.0.9 on 2019-01-18 22:05

from django.db import migrations, models
import surveys.models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0008_invitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='token',
            field=models.CharField(default=surveys.models.generate_random_token, max_length=32),
        ),
    ]
