# Generated by Django 2.0.9 on 2019-01-28 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("surveys", "0010_answer")]

    operations = [
        migrations.RemoveField(model_name="answer", name="option"),
        migrations.AddField(
            model_name="answer",
            name="options",
            field=models.ManyToManyField(to="surveys.Option"),
        ),
    ]
