# Generated by Django 2.0.9 on 2019-01-28 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("surveys", "0011_auto_20190128_1752")]

    operations = [
        migrations.AddField(
            model_name="question",
            name="qtype",
            field=models.CharField(
                choices=[("SINGLE", "Radio"), ("MULTI", "Checkboxes")],
                default="SINGLE",
                max_length=9,
            ),
        )
    ]
