# Generated by Django 2.0.9 on 2019-01-31 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0012_question_qtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='help_text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
