# Generated by Django 2.0.9 on 2019-02-01 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0014_auto_20190131_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='qtype',
            field=models.CharField(choices=[('SINGLECHOICE', 'Radio'), ('MULTICHOICE', 'Checkboxes')], default='SINGLECHOICE', max_length=9),
        ),
    ]
