# Generated by Django 2.0.9 on 2019-02-01 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0016_auto_20190201_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='qtype',
            field=models.CharField(choices=[('SINGLECHOICE', 'Radio'), ('MULTICHOICE', 'Checkboxes'), ('SELECT', 'Dropdown')], default='SINGLECHOICE', max_length=20),
        ),
    ]
