# Generated by Django 2.0.9 on 2019-02-01 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0017_auto_20190201_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='qtype',
            field=models.CharField(choices=[('SINGLECHOICE', 'Radio'), ('MULTICHOICE', 'Checkboxes'), ('SELECT', 'Dropdown'), ('TEXT', 'Text')], default='SINGLECHOICE', max_length=20),
        ),
    ]
