# Generated by Django 2.0.9 on 2019-02-01 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0018_auto_20190201_1905'),
    ]

    operations = [
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='value',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='surveys.Value'),
        ),
    ]
