# Generated by Django 2.0.9 on 2019-02-03 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0019_auto_20190201_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='qtype',
            field=models.CharField(choices=[('SINGLECHOICE', 'Radio'), ('MULTICHOICE', 'Checkboxes'), ('SELECT', 'Select (Dropdown)'), ('TEXT', 'Text'), ('ESSAY', 'Essay'), ('INTEGER', 'Integer'), ('EMAIL', 'Email')], default='SINGLECHOICE', max_length=20),
        ),
    ]
