# Generated by Django 2.0.9 on 2019-02-06 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('surveys', '0020_auto_20190203_1747'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisplayLogic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='DisplayByOptions',
            fields=[
                ('displaylogic_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='surveys.DisplayLogic')),
                ('options', models.ManyToManyField(to='surveys.Option')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('surveys.displaylogic',),
        ),
        migrations.CreateModel(
            name='DisplayByValue',
            fields=[
                ('displaylogic_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='surveys.DisplayLogic')),
                ('value', models.CharField(max_length=100)),
                ('condition', models.CharField(choices=[('==', '=='), ('>=', '>='), ('<=', '<='), ('contains', 'contains')], default='==', max_length=20)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('surveys.displaylogic',),
        ),
        migrations.AddField(
            model_name='displaylogic',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_surveys.displaylogic_set+', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='displaylogic',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.Question'),
        ),
    ]
