# Generated by Django 2.0.9 on 2019-02-06 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0021_auto_20190206_1335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='displaylogic',
            name='question',
        ),
        migrations.AddField(
            model_name='question',
            name='display_logic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='surveys.DisplayLogic'),
        ),
    ]
