# Generated by Django 2.0.9 on 2019-02-06 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0022_auto_20190206_1404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='display_logic',
        ),
        migrations.AddField(
            model_name='displaylogic',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='surveys.Question'),
        ),
    ]
