# Generated by Django 2.0.9 on 2019-02-06 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0023_auto_20190206_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='displaylogic',
            name='question',
        ),
        migrations.AddField(
            model_name='displaylogic',
            name='shown_question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trigger_questions', to='surveys.Question'),
        ),
        migrations.AddField(
            model_name='displaylogic',
            name='trigger_question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shown_question', to='surveys.Question'),
        ),
    ]
