# Generated by Django 2.0.9 on 2019-02-06 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0024_auto_20190206_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='displaybyvalue',
            name='condition',
            field=models.CharField(choices=[('==', '=='), ('>=', '>='), ('<=', '<='), ('contains', 'contains'), ('containsNoCase', 'containsNoCase')], default='==', max_length=20),
        ),
    ]
