# Generated by Django 2.0.9 on 2019-02-11 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0025_auto_20190206_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
