# Generated by Django 2.0.9 on 2019-02-20 12:26

from django.db import migrations, models
import surveys.models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0026_auto_20190211_0157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='displaylogic',
            name='shown_question',
        ),
        migrations.AddField(
            model_name='displaylogic',
            name='shown_element',
            field=models.ForeignKey(null=True, on_delete=surveys.models.NON_POLYMORPHIC_CASCADE, related_name='trigger_questions', to='surveys.Question'),
        ),
        migrations.AlterField(
            model_name='displaylogic',
            name='trigger_question',
            field=models.ForeignKey(null=True, on_delete=surveys.models.NON_POLYMORPHIC_CASCADE, related_name='shown_element', to='surveys.Question'),
        ),
    ]
