# Generated by Django 2.0.9 on 2019-01-10 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondents', '0002_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='address_detail',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='hospital',
            name='address_detail',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
