# Generated by Django 2.0.9 on 2019-01-10 19:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondents', '0003_auto_20190110_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='contact_tel',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AddField(
            model_name='hospital',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='department',
            name='address',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='department',
            name='address_detail',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='department',
            name='city',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='department',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='department',
            name='contact_name',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='department',
            name='country',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='department',
            name='state_province',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='department',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='address',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='address_detail',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='city',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='country',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='state_province',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
