# Generated by Django 2.0.9 on 2019-01-10 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('correspondents', '0004_auto_20190110_1935'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='contact_tel',
            new_name='contact_phone',
        ),
        migrations.RenameField(
            model_name='hospital',
            old_name='phone_number',
            new_name='phone',
        ),
    ]
