# Generated by Django 2.0.9 on 2019-01-10 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('correspondents', '0006_hospital_contact_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='contact_name',
        ),
    ]
