# Generated by Django 2.0.9 on 2019-01-17 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondents', '0007_remove_hospital_contact_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='address',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='department',
            name='city',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='department',
            name='country',
            field=models.CharField(blank=True, max_length=45),
        ),
        migrations.AlterField(
            model_name='department',
            name='state_province',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='address',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='city',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='country',
            field=models.CharField(blank=True, max_length=45),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='state_province',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
